import { Metadata } from 'next';
import GlobalStyles from './styles/GlobalStyles';
import { GameProvider } from './services/GameContext';

export const metadata: Metadata = {
  title: 'RuneHunt',
  description: 'Rune Hunt Game',
};

// export const metadata = {
//   title: 'Next.js',./styles/GlobalStyles
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/assets/rune.png" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover"
        />
      </head>
      <body>
        <GameProvider>

        <GlobalStyles />
        {children}
        </GameProvider>
      </body>
    </html>
  );
}
